### ISSUE TITLE
Possible SQL Injection

### ISSUE THREAD

**Issue by syserr0r** [tyger07/BF4-Server-Stats#14]
Is there any reason the soldierName couldn't be malicious and used for SQL injectikon?

**Comment by tyger07** [comment]
It uses mysql_real_escapestring and only allows certain characters.
Should be harmless.

<div>-------- Original message --------</div><div>From: Anthony <notifications@github.com> </div><div>Date:04/17/2015  13:06  (GMT-08:00) </div><div>To: tyger07/BF4-Server-Stats <BF4-Server-Stats@noreply.github.com> </div><div>Subject: [BF4-Server-Stats] Possible SQL Injection (#14) </div><div>
</div>Is there any reason the soldierName couldn't be malicious and used for SQL injectikon?

**Comment by syserr0r** [comment]
* Make your name in origin something like `%'; DROP TABLE tbl_playerstats; --`
* Join and leave Battlefield server
* Visit BF4- Server-Stats page for server
* [optional] Search for player `tbl_playerstats`

The [$SoldierName is assigned](https://github.com/tyger07/BF4-Server-Stats/blob/f940610bb98f017f0c6cd1fa3ccb1cae8ad91a97/index.php#L134) from the database and then trusted and [used in player stats query](https://github.com/tyger07/BF4-Server-Stats/blob/f940610bb98f017f0c6cd1fa3ccb1cae8ad91a97/common/player/player.php#L163)

**Comment by tyger07** [comment]
Spaces, single quotations, and double quotations are filtered out before it is processed.  If such a soldiername existed, the stats page would say that the player didn't exist.

<div>-------- Original message --------</div><div>From: Anthony <notifications@github.com> </div><div>Date:04/17/2015  18:48  (GMT-08:00) </div><div>To: tyger07/BF4-Server-Stats <BF4-Server-Stats@noreply.github.com> </div><div>Cc: tyger07 <ty_ger07@hotmail.com> </div><div>Subject: Re: [BF4-Server-Stats] Possible SQL Injection (#14) </div><div>
</div>
* Make your name in origin something like `%'; DROP TABLE tbl_playerstats; --`
* Join and leave Battlefield server
* Visit BF4- Server-Stats page for server
* [optional] Search for player `tbl_playerstats`

The [$SoldierName is assigned](https://github.com/tyger07/BF4-Server-Stats/blob/f940610bb98f017f0c6cd1fa3ccb1cae8ad91a97/index.php#L134) from the database and then trusted and [used in player stats query](https://github.com/tyger07/BF4-Server-Stats/blob/f940610bb98f017f0c6cd1fa3ccb1cae8ad91a97/common/player/player.php#L163)

---

**Comment by syserr0r** [comment]
After a nights sleep and coming back to this, it looks like it could only work in an extremely edge case.

I hadn't followed `$SoldierName` fully until now, and it looks like it can be one of two pieces of information:
* The `mysqli_real_escape_string`'ed search from $_GET
* The `soldierName` from the database **if** there is an exact match on the name *or* playerid

The only time you could use the `$SoldierName` from the database for injection is if:
*  `$SoldierName` was set from the database  (the only way being `$playerid` as we can't match the name exactly as our search would be escaped)
* [`$soldier_found == 0`](https://github.com/tyger07/BF4-Server-Stats/blob/f940610bb98f017f0c6cd1fa3ccb1cae8ad91a97/common/player/player.php#L88) but `$soldierName` is still from the DB
  * This would require the following query to return 1 row:
  * ```SELECT ...
FROM tbl_playerdata tpd
INNER JOIN tbl_server_player tsp ON tsp.PlayerID = tpd.PlayerID
INNER JOIN tbl_playerstats tps ON tps.StatsID = tsp.StatsID
WHERE tpd.PlayerID = {$PlayerID}
AND tpd.GameID = {$GameID}
AND tsp.ServerID IN ({$valid_ids})```
  * While at the same time this query must return 0 or more than 1 rows:
  *  ```SELECT ...
FROM tbl_playerstats tps
INNER JOIN tbl_server_player tsp ON tsp.StatsID = tps.StatsID
INNER JOIN tbl_playerdata tpd ON tsp.PlayerID = tpd.PlayerID
WHERE tpd.PlayerID = {$PlayerID}
AND tpd.GameID = {$GameID}
AND tsp.ServerID IN ({$valid_ids})
GROUP BY tpd.PlayerID```

Additionally, there is a 30 character limit on Origin names and only `A-Za-z0-9_-` are allowed, which while hex encoding would likely work, the character limit hampers it's usefulness.

Using a BF4-Server-Stats page which has a stats shared with non-origin games (such as Bad Company 2) would probably be the only practical way to do anything with this.

**Comment by tyger07** [comment]
See also issue "XSS Attacks":

https://github.com/tyger07/BF4-Server-Stats/issues/20

Further comments after closing the above issue and the above linked issue:

As far as I am aware, there are no SQL injection or XSS attack vectors remaining in this code.  I should say that I know that a person can purposely break the code and produce errors if they wanted; especially if they don't go through index.php and instead go through a sub-page and purposely give it false or erroneous data.  But those hack pokes and prods would only produce erroneous output in their browser and would not permanently damage any of the stats pages, nor damage any information in the stats database, nor be share information across connections to break the experience for other users nor collect other users' information.

All of that aside, I am aware of a "Type 2" or "Second-Order" attack vector which could still be possible.  Such an attack would require the attacker to input the attack into the database and then have the stats page execute it as trusted content.  I do not believe such an attack is possible using the chat log page due to the way chat content is not trusted and sanitized.  But, I think that it would be possible only by the use of using specific player soldier names.  Fortunately, as far as I am aware, there are no characters which EA/Origin/Battlelog allow which would allow a player to pick a dangerous soldier name which could be used in a second-order attack.

**Comment by tyger07** [comment]
Although I do not believe that attackers would have been able to leverage second-order attack vectors, I tested second-order attack vectors by modifying the data in the database directly and confirmed that it would be theoretically possible if the attacker had necessary means to insert the required characters into the database.  The code has now been modified to protect against second-order attack vectors.
