### ISSUE TITLE
Leaderboard isnt pulling "Top Players"

### ISSUE THREAD

**Issue by mikedevita** [tyger07/BF4-Server-Stats#15]
Not sure whats up with my stats page but our [leaderboard](http://stats.otcclan.com/index.php?p=leaders) doesn't show top players, it does however show top 20 players this week. Is there a certain way i need to set the settings in procon to get this to work right?

**Comment by tyger07** [comment]
The first page of the leaderboard is on a 12 hour cache.  The function of counting the number of players in the database is also on a 12 hour cache.
If it is a new stats database the leaderboard will look funny for a while.  As more and more players get added to the database and as players scores get large, you will probably stop noticing that some stats are 12 hours behind reality.

**Comment by mikedevita** [comment]
the first page doesn't even show anything though, stats have been running since mid september.

**Comment by tyger07** [comment]
My reply #2:
It seems that my stats page is being denied access to modify your stats database.  It appears that the stats page is logging into your stats database as a user who only has read privileges.  Because it is unable to create cache tables for storing values into, when it tries to later read those missing values, it comes up empty.  That's why it says there are no player stats.

**Comment by mikedevita** [comment]
Yes, duh.. this fixed my issue now. you can close this. Thanks.

**Comment by tyger07** [comment]
I am glad that we were able to figure it out together. :)
