### ISSUE TITLE
Differense between global rank and top players (week)

### ISSUE THREAD

**Issue by dbohry** [tyger07/BF4-Server-Stats#16]
Hi!

I want to understand why the score of the current week players is higher than the global score.

Keep the good work!

**Comment by tyger07** [comment]
It's a big in XpKiller's Procon Stats Logger code.  Player scores in session stats are higher than they should be.  There's nothing I could do to fix it since the error occurs before my stats page uses the data.
It is assumed that all players' scores are equally inflated by some percentage and therefore still relevant for comparison purposes.

**Comment by tyger07** [comment]
I meant 'bug' not 'big'.

**Comment by dbohry** [comment]
Fine! Thanks for the quick awnser!
