### ISSUE TITLE
XSS Attacks

### ISSUE THREAD

**Issue by zer0sec** [tyger07/BF4-Server-Stats#20]
This status page is vulnerable to xss attacks
few examples. they will only show up in firefox any other browser probably won't show if you're using chrome etc
1st
/stats/index.php?o=ASC_</script><script>prompt(993968)</script>&p=leaders&r=SoldierName&sid=15

2nd example
/stats/common/countries/countries.php?c=DE%2cRU%2cGB%2cFR%2cPL%2cSE%2cNL%2cTR%2cIT%2cES%2cFI%2cDK%2cAT%2cUA%2cBE%2cCZ%2cNO%2cCH%2cHU%2cIL'%22()%26%25<ScRiPt%20>prompt(902136)</ScRiPt>&gid=1&sid=15

**Comment by tyger07** [comment]
"1st" example, I do not see.  "ASC_" is not a valid input.

common/leaders/leaders.php:
`
if($order != 'DESC' AND $order != 'ASC')
	{
		// unexpected input detected
		// use default instead
		$order = 'DESC';
		$nextorder = 'ASC';
	}
`

2nd example, I see.
It should have been something like:
`if(!empty($_GET['c']) && strlen($_GET['c']) == 2 && !(is_numeric($_GET['c'])))`
like it is in case.php for variable cc

**Comment by zer0sec** [comment]
Glad to help

**Comment by tyger07** [comment]
Since I no longer own a game server, no longer own a layer server, no longer own a web server, and no longer have a stats database, it will take me a while to build an environment where I can make and test the necessary changes.

**Comment by zer0sec** [comment]
Couldn't you simply just use xampp?

**Comment by tyger07** [comment]
Yes, exactly what I am going to do.  But, it isn't set up yet and I have no stats database.  I listed all the things you would usually use to get to where I need to go.

**Comment by zer0sec** [comment]
Ok i see, Well i don't have a battlefield server or i'd help you pal, If you ever fix this if you wouldn't mind adding me to change log for finding the vuln thanks.

**Comment by tyger07** [comment]
Code has been updated.  All inputs have been further sanitized specifically to fit even more within the bounds of what I expect the input to be plus strip_tags() is used to strip HTML tags from all inputs.

**Comment by zer0sec** [comment]
Glad to help.

**Comment by tyger07** [comment]
As far as I am aware, there are no SQL injection or XSS attack vectors remaining in this code.  I should say that I know that a person can purposely break the code and produce errors if they wanted; especially if they don't go through index.php and instead go through a sub-page and purposely give it false or erroneous data.  But those hack pokes and prods would only produce erroneous output in their browser and would not permanently damage any of the stats pages, nor damage any information in the stats database, nor be share information across connections to break the experience for other users nor collect other users' information.

All of that aside, I am aware of a "Type 2" or "Second-Order" attack vector which could still be possible.  Such an attack would require the attacker to input the attack into the database and then have the stats page execute it as trusted content.  I do not believe such an attack is possible using the chat log page due to the way chat content is not trusted and sanitized.  But, I think that it would be possible only by the use of using specific player soldier names.  Fortunately, as far as I am aware, there are no characters which EA/Origin/Battlelog allow which would allow a player to pick a dangerous soldier name which could be used in a second-order attack.

**Comment by syserr0r** [comment]
Not that this is neccessarily relevant any more, but PHP's `is_numeric` considers hex and exponential notation acceptable. I know of SQL injection attacks that use hex to pass filters and/or avoid detection by IDS.

Food for thought.

**Comment by tyger07** [comment]
Although I do not believe that attackers would have been able to leverage second-order attack vectors, I tested second-order attack vectors by modifying the data in the database directly and confirmed that it would be theoretically possible if the attacker had necessary means to insert the required characters into the database.  The code has now been modified to protect against second-order attack vectors.
