### ISSUE TITLE
Nginx support

### ISSUE THREAD

**Issue by samoz83** [tyger07/BF4-Server-Stats#26]
Is it possible to have Nginx support for the signature generation? Can't seem to get it to work.

**Comment by tyger07** [comment]
I don't know anything about Nginx, but the signature should behave just like any other image, therefore it should require nothing special in order to work with Nginx.  Just incorporate it into Nginx the same way you incorporate any other image in Nginx.

*BASE_URL*/common/signature/signaturepid*PLAYER_ID*fav0.png

For example:
<img src="www.mywebsite.com/bf4stats/common/signature/signaturepid12345fav0.png" />

**Comment by samoz83** [comment]
Forgot to post this years ago but if others are running nginx and want to replicate the .htaccess for the banners and signatures creation add the below to your websites config.

```
location ~ /stats/common/server/(.*)\.png* {
     rewrite ^/(.*)\.png* /$1.php last;
}

location ~ /stats/common/server-banner/(.*)\.png* {
      rewrite ^/(.*)(sid)(.*\d)(.png) /$1.php?$2=$3 last;
}

location ~ /stats/common/signature/(.*)\.png* {
      rewrite ^(.*)(pid)(.*\d)(fav)(.*\d)(.*) $1.php?$2=$3&$4=$5 last;
}
```
